FROM python:3.13.1-bookworm
WORKDIR /app

ARG MGA_TOKEN
ENV MGA_TOKEN=${MGA_TOKEN}

ARG KW_ASSISTANT_ID
ENV KW_ASSISTANT_ID=${KW_ASSISTANT_ID}

ARG QUERY_ASSISTANT_ID
ENV QUERY_ASSISTANT_ID=${QUERY_ASSISTANT_ID}

ARG ANALYSIS_ASSISTANT_ID
ENV ANALYSIS_ASSISTANT_ID=${ANALYSIS_ASSISTANT_ID}

ARG DATABASE
ENV DATABASE=${DATABASE}

ARG WORKGROUP
ENV WORKGROUP=${WORKGROUP}

ARG S3_OUTPUT
ENV S3_OUTPUT=${S3_OUTPUT}

ARG DATA_SOURCE
ENV DATA_SOURCE=${DATA_SOURCE}

ARG ATHENA_ACCESS_KEY
ENV ATHENA_ACCESS_KEY=${ATHENA_ACCESS_KEY}

ARG ATHENA_SECRET_ACCESS_KEY
ENV ATHENA_SECRET_ACCESS_KEY=${ATHENA_SECRET_ACCESS_KEY}

COPY hse-mining-frontend hse-mining-frontend
COPY pyproject.toml .
COPY README.md .
COPY styles.css .
RUN pip install .

EXPOSE 8501
CMD ["streamlit", "run", "hse-mining-frontend/frontend.py"]