import streamlit as st
from awsconnection import load_data
from interactions import get_generated_query, analyze_observations
from transformations import transform_observation
from filters import STATUS, DIVISION, OBSERVATIONCAUSE   

def query_sequence(user_input, session_state: dict) -> None:
    with st.spinner('Generating SQL Query based on your request...'):
        generated_query, _ = get_generated_query(user_input, session_state)
    with st.expander("Generated SQL Query", expanded=False):
        st.write(f"Query: {generated_query}")

    if not generated_query:
        st.error("No SQL query generated by LLM Agent")

    else:
        with st.spinner('Running the generated SQL query against HSE database...'):
            df = load_data(generated_query, {})
            if len(df) == session_state.hard_limit:
                st.warning(f"""Data limit of {session_state.hard_limit} observations reached. 
                           Try adjusting your query and/or filters to get more specific results!""")
        with st.expander("Query Result", expanded=False):
            st.write("Query Result:")
            st.dataframe(df)
        with st.spinner('Analyzing the retrieved data...'):
            observations_sorted, columns, rows = transform_observation(df)
            result = analyze_observations(observations_sorted, user_input, columns, rows)
        if result:
            st.write(f"Analysis: {result}")
        else:
            st.error("AI analysis failed - try again with a smaller dataset")

def sidebar(session_state: dict) -> None:  
    with st.sidebar:
        st.header("Filters")
        session_state.filters = {
            "Created": st.date_input("Created", []),
            "Status": st.selectbox("Status", STATUS),
            "Division": st.selectbox("Division", DIVISION),
            "Observationcause": st.selectbox("Observationcause", OBSERVATIONCAUSE),
        }
        st.markdown(
            """
            <div class="tooltip">ℹ️
                <span class="tooltiptext">EXPERIMENTAL: Increasing the limit may retrieve more data, but in extreme cases can crash the AI.</span>
            </div>
            """,
            unsafe_allow_html=True
        )            
        session_state.hard_limit = st.number_input("Hard Limit for Observations returned", value=300, min_value=1)

